name: ${project.name}
version: ${project.version}
description: ${description}

main: com.github.groundbreakingmc.essentialswarps.EssentialsWarps
api-version: '1.16'
depend: [ Essentials ]

author: GroundbreakingMC
website: ${url}

permissions:
  essentials.delwarp.all:
    default: false
  essentials.delwarp.server:
    default: false
  essentials.setwarp.bypasslimit:
    default: false